sudo: required
language: node_js
node_js: "11"
env:
  -distribution: ubuntu
   version: xenial
  -distribution: debian
   version: jessie

addons:
  sonarcloud:
    organization: "diegotony-github"
    token:
      secure: 


